# Previous content of build_book.py...

# Add the new compound swaps
COMPOUND_SWAPS = [
    # ... Other swaps ...
    ("Thou art", "You are"),
    ("thou art", "you are"),
    ("Thou wast", "You were"),
    ("thou wast", "you were"),
    # ... Remaining swaps ...
]

# Following content of build_book.py...